services:
    - type: web
      name: cesizen
      runtime: php
      buildCommand: "./render-build.sh"
      startCommand: "php -S 0.0.0.0:$PORT -t public/"
      envVars:
          - key: APP_ENV
            value: prod
          - key: APP_SECRET
            generateValue: true
          - key: DATABASE_URL
            fromDatabase:
                name: cesizen-db
                property: connectionString

databases:
    - name: cesizen-db
      databaseName: cesizen
      user: cesizen_user
